targets:
  $default:
    builders:
      freezed:
        generate_for:
          include:
            - lib/**/*state.dart
            - lib/model/entities/**/*.dart
      json_serializable:
        generate_for:
          include:
            - lib/model/entities/**/*.dart
        options:
          any_map: true
          explicit_to_json: true
